#!/bin/sh
set -e

LUATYPE=$1
if [ -z ${LUATYPE} ] ; then
  LUATYPE=5.1
fi
if [ ${LUATYPE} = "jit" ] ; then
  VER=5.1
else
  VER=${LUATYPE}
fi

luarocks config lua_version ${VER}
eval `luarocks path`
lua${LUATYPE} test_main_normal.lua
lua${LUATYPE} test_encoding_error.lua
